### DISCUSSION TITLE
Adding more tags to a single bake target

### DISCUSSION THREAD

**Discussion by 0yi0** [docker/bake-action#243] [Q&A] [answered]
I'm using matrix to generate multiple images like
```hcl
target "base" {
  matrix = {
    version = ["20.04", "22.04", "24.04"]
  }
  name = "ubuntu-${replace(version, ".", "")}"
  tags = ["my/image:ubuntu-${version}"]
  ...
}
```

Is there any way to re-tag images without overriding original tags like we do in command line?
```sh
docker tag my/image:ubuntu-24.04 my/image:ubuntu-latest
```

I currently push docker images directly with `docker/bake-action`. I think it can be done like
```yml
- uses: docker/bake-action@v5
  with:
    push: true
    set: |
      ubuntu-2404.tags = [<original tags ...>, "my/image:ubuntu-latest"]
```
But in this way I need to rewrite the whole array instead of just adding a tag.

Is there any way to achieve something like
```yml
- uses: docker/bake-action@v5
  with:
    push: true
    set: |
      ubuntu-2404.tags += ["my/image:ubuntu-latest"]
```
So that we don't need to touch any existing tags?

### Alt solutions (My workarounds)
I'm currently using a new target as the original one as its context.
```hcl
target "latest" {
  inherits = ["ubuntu-2404"]
  contexts = {
    "my/image:ubuntu-24.04" = "target:ubuntu-2404"
  }
  tags = ["my/image:ubuntu-latest"]
}
```

I also saw a 4yo discussion https://github.com/docker/buildx/issues/427 to allow optional tagging.
