### DISCUSSION TITLE
Build summary shows all images with name `docker`

### DISCUSSION THREAD

**Discussion by mrfelton** [docker/bake-action#248] [Q&A]
H,
I'm building multiple apps from a bake file and the build summary in GHA shows them all with the name `docker`, which makes it not very useful since I don't know which build summary relates which app.

<img width="436" alt="image" src="https://github.com/user-attachments/assets/b1a426ad-0ffe-4ffe-891c-6dfdf99e8a2a">

Some info about my setup:

1. All apps use the same context
2. All apps use the same dockerfile, but with different build args
3. The bake is invoked like this

```yml
    - name: 'Setup Buildx'
      uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # pin@v3.6.1
      with:
        buildkitd-config-inline: |
          [worker.oci]
            # More than 6 parallel builds can cause OOM on our big runners.
            max-parallelism = 6

    - name: 'Docker metadata'
      id: meta
      uses: docker/metadata-action@8e5442c4ef9f78752691e2d8f8d19755c6f78e81 # pin@v5.5.1

    - name: 'Build and push'
      uses: docker/bake-action@76cc8060bdff6d632a465001e4cf300684c5472c # pin@v5.7.0
      env:
        TAG: ${{ inputs.tag }}
      with:
        workdir: docker
        load: false
        targets: ${{ steps.sanitize-projects.outputs.projects }}
        push: ${{ inputs.push }}
        files: |
          ./docker-bake.json
          ./docker-bake.override.json
          ${{ steps.meta.outputs.bake-file-labels }}
          ${{ steps.meta.outputs.bake-file-labels }}
```

An excert from the bake file:

```json
{
  "target": {
    "example-app-admin": {
      "inherits": [
        "zapgeneric"
      ],
      "dockerfile": "Dockerfile.zapgeneric",
      "args": {
        "PROJECT": "admin",
      },
      "tags": [
        "admin:${TAG}"
      ],
      "contexts": {
        "ctx": "target:ctx"
      }
    },
    "example-adapter-api": {
      "inherits": [
        "zapgeneric"
      ],
      "dockerfile": "Dockerfile.zapgeneric",
      "args": {
        "PROJECT": "adapter",
      },
      "tags": [
        "adapter:${TAG}"
      ],
      "contexts": {
        "ctx": "target:ctx"
      }
    }
}
```
