### DISCUSSION TITLE
How can I add multiple tags for the same image?

### DISCUSSION THREAD

**Discussion by jdkent** [docker/bake-action#296] [Q&A] [answered]
I'm treating this as a list, this is not the correct syntax:

```yml
name: Build and push
        uses: docker/bake-action@v2
        with:
          files: docker-compose.yml
          push: true
          load: false
          pull: false
          set: |
              worker.tags=["ghcr.io/${{ env.OWNER_LC }}/neurovault:${{ hashFiles('**/neurovault/**') }}", "ghcr.io/${{ env.OWNER_LC }}/neurovault:${{ env.SANITIZED_BRANCH_NAME }}"]
              worker.cache-from=type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/neurovault:${{ hashFiles('**/neurovault/**') }}
              worker.cache-from=type=gha,scope=cached-neurovault
              worker.cache-to=type=gha,scope=cached-neurovault,mode=max
              django.tags=["ghcr.io/${{ env.OWNER_LC }}/neurovault_fs:${{ hashFiles('**/neurovault/**') }}", "ghcr.io/${{ env.OWNER_LC }}/neurovault_fs:${{ env.SANITIZED_BRANCH_NAME }}"]
              django.cache-from=type=registry,ref=ghcr.io/${{ env.OWNER_LC }}/neurovault_fs:${{ hashFiles('**/neurovault/**') }}
              django.cache-from=type=gha,scope=cached-neurovault_fs
              django.cache-to=type=gha,scope=cached-neurovault_fs,mode=max
```

Does anyone know the correct syntax for specifying multiple tags?

Thank you!
