### ISSUE TITLE
Feat: registry option

### ISSUE THREAD

**Issue by koenverburg** [docker/bake-action#10]
Hi guys, 

Really like this action, the only thing I found missing is the option to point to another registry like GitHub's container registry.
Is there a way to set the registry with the `set` option or will this be a new feature?

Thanks in advanced,

Koen

**Comment by crazy-max** [comment]
@koenverburg 

> Is there a way to set the registry with the `set` option or will this be a new feature?

I think you're talking about specifying a tag that would be assigned to multiple registries? If so you could use the [Docker meta action](https://github.com/crazy-max/ghaction-docker-meta) that can handle a [dedicated bake definition](https://github.com/crazy-max/ghaction-docker-meta#bake-definition) for this purpose with a special target called `ghaction-docker-meta`:

```hcl
// docker-bake.hcl

target "ghaction-docker-meta" {}

target "build" {
  inherits = ["ghaction-docker-meta"]
  context = "./"
  dockerfile = "Dockerfile"
  platforms = [
    "linux/amd64",
    "linux/arm/v6",
    "linux/arm/v7",
    "linux/arm64",
    "linux/386",
    "linux/ppc64le"
  ]
}
```

Your workflow will look like this:

```yaml
name: ci

on:
  push:
    branches:
      - '**'
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: |
            name/app
            ghcr.io/username/repo
          tag-sha: true
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Build
        uses: docker/bake-action@v1
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
          targets: |
            build
```

Content of the generated `${{ steps.docker_meta.outputs.bake-file }}` file will look like this:

```json
{
  "target": {
    "ghaction-docker-meta": {
      "tags": [
        "name/app:1.1.1",
        "name/app:1.1",
        "name/app:latest",
        "ghcr.io/username/repo:1.1.1",
        "ghcr.io/username/repo:1.1",
        "ghcr.io/username/repo:latest"
      ],
      "labels": {
        "org.opencontainers.image.title": "Hello-World",
        "org.opencontainers.image.description": "This your first repo!",
        "org.opencontainers.image.url": "https://github.com/octocat/Hello-World",
        "org.opencontainers.image.source": "https://github.com/octocat/Hello-World",
        "org.opencontainers.image.version": "1.1.1",
        "org.opencontainers.image.created": "2020-01-10T00:30:00.000Z",
        "org.opencontainers.image.revision": "90dd6032fac8bda1b6c4436a2e65de27961ed071",
        "org.opencontainers.image.licenses": "MIT"
      },
      "args": {
        "DOCKER_META_IMAGES": "name/app,ghcr.io/username/repo",
        "DOCKER_META_VERSION": "1.1.1"
      }
    }
  }
}
```

Live example with Diun project:

* [Bake def](https://github.com/crazy-max/diun/blob/9079adefcdb9b9cd34758f5fc58521c8e398509f/docker-bake.hcl)
* [Workflow](https://github.com/crazy-max/diun/blob/9079adefcdb9b9cd34758f5fc58521c8e398509f/.github/workflows/build.yml)
* [Build](https://github.com/crazy-max/diun/runs/1865352429?check_suite_focus=true)

**Comment by koenverburg** [comment]
@crazy-max I updated my build configuration but is still fails with this error.
![image](https://user-images.githubusercontent.com/10489237/107854520-a6b5bd00-6e1c-11eb-9120-87b45fe1b9e3.png)

The login to GHCR works...

I also looked at the builds/workflows from your diun project but I don't see any noticeable differences, as far as my knowledge does about buildx

Links:
[pipeline](https://github.com/koenverburg/dotfiles/runs/1894005420?check_suite_focus=true#step:8:1356)
[workflow](https://github.com/koenverburg/dotfiles/blob/feature%2Fdocker-validation-build/.github/workflows/docker.yml)

Hope to hear from you.

**Comment by crazy-max** [comment]
@koenverburg Ok you're using a compose definition with bake. The Docker meta action can't handle that type of definition unfortunately. As you can see in your pipeline, [tags are not appended](https://github.com/koenverburg/dotfiles/runs/1894005420?check_suite_focus=true#step:8:19) because `ghaction-docker-meta` target does not exist:

![image](https://user-images.githubusercontent.com/1951866/107857227-0c0dac00-6e25-11eb-8df0-37642a3bcc77.png)

What you can do is creating a simple `docker-bake.hcl` with the following content to allow inheritance with the meta bake definition:

```hcl
// docker-bake.hcl

target "ghaction-docker-meta" {}

target "build" {
  inherits = ["ghaction-docker-meta"]
  context = "./"
  dockerfile = "Dockerfile"
}
```

And update the build step in your workflow with:

```yaml
      - name: Build and push
        uses: docker/bake-action@master
        with:
          push: true
          #targets: default
          Files: |
            ./docker-bake.hcl
            ${{ steps.docker_meta.outputs.bake-file }}
```

Also multi-platform is not yet supported with compose definition so I suggest to keep your HCL def for build/release and your compose def as a runtime def.
