### ISSUE TITLE
Builds not using local cache 

### ISSUE THREAD

**Issue by cristian-heredia** [docker/bake-action#108]
### Behaviour
Docker compose is not using cache for `docker compose run` commands. I'm probably making a silly mistake somewhere, but I can't quite figure out where or how. 

#### Steps to reproduce this issue
I have a fairly simple workflow that I'm trying to get to use local cache for Docker compose 

#### Expected behaviour
I was hoping this workflow would utilize local cache to build compose containers. 

#### Actual behaviour
 The `Build stack` , `Load stack` and `Compose up` steps do appear to use the cached layers; However,  `Run static checks` rebuilds the whole stack again. 

```yml
name: ci

on:
  push:
    branches:
      - master
  pull_request:
  # cron schedule for nightly builds
  schedule:
     - cron: '59 23 * * *'
  # allow manual triggering 
  workflow_dispatch:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build stack
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-compose.yml
          load: false
          push: false
          set: |
              *.cache-from=type=gha,scope=cached-stage
              *.cache-to=type=gha,scope=cached-stage,mode=max
      -
        name: Load stack
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-compose.yml
          load: true
          push: false
          set: |
              *.cache-from=type=local,src=/tmp/.buildx-cache
      -
        name: Compose up
        run: |
          docker-compose up -f docker-compose.yml -d --no-build
      -
        name: Run static checks
        run: |
          docker-compose -f docker-compose.yml run --rm python_base black --check --diff .
      -
        name: Compose down
        run: |
          docker-compose -f docker-compose.yml down
```

### Logs

![Screenshot 2023-01-31 at 7 49 35 PM](https://user-images.githubusercontent.com/84160355/215941102-b5191dd3-3c56-4fa0-87bb-54e1c751a72a.png)
Here is another example where the Build process was quick, but Load stack rebuilt the python image, and once again the static checks built the container too. 
![Screenshot 2023-01-31 at 8 15 33 PM](https://user-images.githubusercontent.com/84160355/215944251-faa36a7e-a83e-446b-9827-a547027763d2.png)

**Comment by crazy-max** [comment]
Hi, sorry for the delay

> ```yaml
>       -
>         name: Load stack
>         uses: docker/bake-action@v2.3.0
>         with:
>           files: docker-compose.yml
>           load: true
>           push: false
>           set: |
>               *.cache-from=type=local,src=/tmp/.buildx-cache
> ```

I don't see any steps in your workflow pushing cache to `/tmp/.buildx-cache`. I also don't think you need this step at all. You can just use the `Build stack` step and set `load: true`:

```yaml
      -
        name: Build stack
        uses: docker/bake-action@v2.3.0
        with:
          files: docker-compose.yml
          load: true
          push: false
          set: |
              *.cache-from=type=gha,scope=cached-stage
              *.cache-to=type=gha,scope=cached-stage,mode=max
```

Now for compose, I'm not sure without seeing the compose file. But `docker-compose` is still v1 in the GH runners and does not use BuildKit but the legacy builder. You should use `docker compose` command instead.

To use the cache pushed in `Build stack` step in your compose file you need to set the `cache_from` field: https://docs.docker.com/compose/compose-file/build/#cache_from. Problem is I don't think you should set this field directly in the compose file as building locally would fail because your computer does not have access to the GitHub infrastructure.

It would be better if you could set overrides like [bake does](https://docs.docker.com/engine/reference/commandline/buildx_bake/#set) but with compose:

```
$ docker compose up -f docker-compose.yml -d --set *.build.cache_from=type=gha,scope=cached-stage
```

But don't think compose support this atm. cc @docker/compose-maintainers 

Closing this issue for now but let us know how it goes.
