### ISSUE TITLE
feature: perform push iff all targets succeed

### ISSUE THREAD

**Issue by Nithos** [docker/bake-action#112]
Not sure if this is possible currently but it would be nice to have the `bake-action` only do a push if all targets have been successfully built. 

My typical use case is to provide a group to use for the build, and from that group extract the individual targets within the definition. From this I build a matrix that is then used to parallelize the targets in the actual `bake-action` with their own individual cache locations.

Eg.
Matrix output is
```
[foo,bar]
```

Following that a bake action is triggered using the following
```
 # 2.6 - Build and push Docker Images
- name: Build Images using BuildX Bake
  uses: docker/bake-action@v2
  with:
    files: ./${{ inputs.file }}
    targets: ${{ matrix.target }}
    push: ${{ inputs.push }}
    set: |
      *.cache-from=type=gha,scope=build-${{ matrix.target }}
      *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
```

But since they are independent steps now, it could be where one (`foo`) is fast and succeeds and is pushed into the registry, while the 2nd one (`bar`) takes longer and eventually fails. This causes the issue that the registry contains inconsistent release versions of the images which is a problem.

Is there a way around this, or is the approach overall flawed?
