### ISSUE TITLE
v3 breaks build for *.output=type=docker,dest

### ISSUE THREAD

**Issue by darthmaim** [docker/bake-action#131]
### Behaviour

After updating to docker/bake-action@v3.0.0 from docker/bake-action@v2.3.0 my build breaks, because I am exporting the image and export does not support provenance metadata. Setting `provenance: false` fixes the build.

This should either be marked clearly as breaking change in the v3 release or the default should changed to `provenance: false`.

#### Steps to reproduce this issue

1. Use the default docker/bake-action@v3 and set *.output=type=docker,dest=/tmp/image.tar

#### Expected behaviour

Build works without error and docker image gets exported

#### Actual behaviour

```
Error: buildx bake failed with: ERROR: docker exporter does not currently support exporting manifest lists
```

### Configuration

* Repository URL (if public): https://github.com/GW2Treasures/gw2treasures.com/pull/135
* Build URL (if public): https://github.com/GW2Treasures/gw2treasures.com/actions/runs/4731151043/jobs/8395743128

```yml
name: Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  merge_group:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  image:
    name: Build image ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [ web, worker, legacy-importer, database-migration ]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Build the Docker image
      uses: docker/bake-action@v3.0.0
      with:
        files: |
          ./docker-compose.yml
          ./docker-compose.importer.yml
        targets: ${{ matrix.target }}
        set: |
          *.output=type=docker,dest=/tmp/image-${{ matrix.target }}.tar
          *.cache-from=type=gha,scope=build-${{ matrix.target }}
          *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
    - uses: actions/upload-artifact@v3
      with:
        name: docker-image-${{ matrix.target }}
        path: /tmp/image-${{ matrix.target }}.tar
```

### Logs

[logs_377.zip](https://github.com/docker/bake-action/files/11261195/logs_377.zip)
