### ISSUE TITLE
Action does not respect the Builder mirror configuration

### ISSUE THREAD

**Issue by gendergap** [docker/bake-action#134]
### Behaviour

I am running the _bake-action_ in a GitHub pipeline in an isolated company network. Local Dockerfiles that extend public Docker images from Dockerhub thus need to go through a mirror (Artifactory) set up in the same network. It is possible to [configure Builder with such mirror information](https://docs.docker.com/build/ci/github-actions/configure-builder/#registry-mirror) during its setup step. This works well with the "pure" _build-push-action_ (on single Dockerfiles), which honors the mirror and pulls base layers from it instead of _registry-1.docker.io_. But as soon as one switches to using the bake action on multiple Dockerfiles, the mirror is not used anymore.

#### Steps to reproduce this issue

1. Define a GitHub pipeline with a setup step for the Builder that includes an inline mirror configuration
2. In a later step, run the Bake action on the same Builder
3. Add one or some Dockerfiles extending public images
4. Observe the pipeline failure

#### Expected behaviour

I expect that images built by Bake on the customized Builder would honor the mirror configured for Dockerhub and thus pull base images not from registry-1.docker.io but from the mirror site.

#### Actual behaviour

Buildx (according to the output) relentlessly tries to contact Dockerhub directly:

> Error: buildx bake failed with: ERROR: failed to solve: DeadlineExceeded: DeadlineExceeded: DeadlineExceeded: centos:8.3.2011: failed to do request: Head "https://registry-1.docker.io/v2/library/centos/manifests/8.3.2011": dial tcp 34.194.164.123:443: i/o timeout

### Configuration

```yml
    steps:
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        id: setup-builder
        with:
          config-inline: |
            [registry."docker.io"]
              mirrors = ["dockerhub-remote.artifactory.company.int"]
      -
        name: Build and push
        uses: docker/bake-action@v2
        with:
          builder: ${{ steps.setup-builder.outputs.name }}
          workdir: ${{ matrix.image }}
          push: true
```

### Logs

[githubactions-run-log.txt](https://github.com/docker/bake-action/files/11273175/githubactions-run-log.txt)
[githubactions-cleanup-log.txt](https://github.com/docker/bake-action/files/11273174/githubactions-cleanup-log.txt)
