### ISSUE TITLE
Too large metadata cause " Argument list too long" error

### ISSUE THREAD

**Issue by unkcpz** [docker/bake-action#135]
### Behaviour

When I tried to parse the info from build metadata using:

```yml
            - name: Set output variables
              id: bake_metadata
              env:
                  BAKE_METADATA: ${{ steps.bake.outputs.metadata }}
              run: |
                  targets=$(jq -c 'keys' <<< "${BAKE_METADATA}")
                  echo "::set-output name=targets::${targets}"
                  images=$(jq -c '. as $base |[to_entries[] |{"key": (.key|ascii_upcase|sub("-"; "_"; "g") + "_IMAGE"), "value": [(.value."image.name"|split(",")[0]),.value."containerimage.digest"]|join("@")}] |from_entries' <<< "${BAKE_METADATA}")
                  echo "::set-output name=images::${images}"
```

I got the error "Argument list too long".

Is there anyway to workaround this by writing the metadata to some file rather than an environment variable?

### Logs

The log archive is in:
[logs_1206.zip](https://github.com/docker/bake-action/files/11303771/logs_1206.zip)
