### ISSUE TITLE
Everything after # gets eaten in the `set` input, with no way to escape it since v3

### ISSUE THREAD

**Issue by sandhose** [docker/bake-action#136]
#### Steps to reproduce this issue

Set the context like this:

```yaml
- name: Build
  uses: docker/bake-action@v3
  with:
    set: |
      base.context=https://github.com/${{ github.repository }}.git#${{ github.ref }}
```

#### Expected behaviour

`docker bake` should be called with `--set base.context=https://github.com/foo/bar#ref`

or have a way to escape it. I tried putting quotes around, or backslashes, but none of this works.

#### Actual behaviour

`docker bake` should is called with `--set base.context=https://github.com/foo/bar` (without the `#ref`

### Configuration

* Repository URL (if public): https://github.com/matrix-org/matrix-authentication-service
* Build URL (if public): https://github.com/matrix-org/matrix-authentication-service/actions/runs/4784813799/jobs/8506781393#step:9:219
