### ISSUE TITLE
org.opencontainers.image.source is missing from the annotations section of the manifests

### ISSUE THREAD

**Issue by SamirMarin** [docker/bake-action#171]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

Multi-arch images built and pushed using the bake action aren't being linked to their respective GitHub repositories due to the absence of the org.opencontainers.image.source annotation in the OCI image manifests.

We are utilizing the bake action to create and push a multi-arch image to the GitHub OCI registry. While the push to the registry is successful, the image does not get linked to its GitHub repository. Upon reaching out to GitHub support, they indicated the linking issue arises because the org.opencontainers.image.source is absent from the annotations section of the OCI image manifests.

In the bake file definition, I noticed that the label does contain the org.opencontainers.image.source information. However, this seems insufficient as it's not being transferred to the image manifest upon pushing.

From my understanding, for GitHub to link multi-arch images to their corresponding repositories, the org.opencontainers.image.source key in the manifest's annotations field needs to be set.

I'm unsure if this behavior is a bug or if the feature to add the necessary annotations is not yet implemented in the bake action. If it's the latter, I'd be happy to submit a feature issue instead. Any assistance or direction on this matter would be greatly appreciated.

### Expected behaviour

The`org.opencontainers.image.source` key is set in the annotations field of the image manifest.

### Actual behaviour

No `org.opencontainers.image.source` key is set in the annotations field of the image manifest.

### YAML workflow

```yaml
steps:

      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate docker metadata
        id: docker-metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ inputs.owner }}/${{ inputs.name }}
          tags: |
            ${{ inputs.tags }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PKG_TOKEN }}

      - name: Build
        uses: docker/bake-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.PKG_TOKEN }}
        with:
          files: |
            ${{ inputs.bake-files }}
            ${{ steps.docker-metadata.outputs.bake-file }}
          targets: |
            ${{ inputs.targets }}
          push: ${{ inputs.push }}
          set: |
            *.secrets=id=GITHUB_TOKEN
            ${{ inputs.bake-set }}
```
