### ISSUE TITLE
Guideline for leveraging GitHub Actions cache

### ISSUE THREAD

**Issue by felipecrs** [docker/bake-action#196]
Hi,

I believe it would be super helpful to provide some guidelines on how to implement gha caching while using this action.

Docker's documentation also doesn't mention anything about when using bake:

https://docs.docker.com/build/cache/backends/gha/

**Comment by nathanblair** [comment]
A pretty straightforward job like this

```
  services:
    name: Services
    environment: non-prod
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4

      - name: Login to ACR
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.REGISTRY }}
          username: ${{ vars.ARM_CLIENT_ID }}
          password: ${{ secrets.ARM_CLIENT_SECRET }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - uses: docker/bake-action@v5
        env:
          REGISTRY: ${{ vars.REGISTRY }}
        with:
           push: true
           set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
```

has not been successful in caching. It keeps creating Actions Caches and quickly fills up the Actions Cache size.
