### ISSUE TITLE
Cache not working

### ISSUE THREAD

**Issue by FezVrasta** [docker/bake-action#245]
### Contributing guidelines

- [X] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [X] The documentation does not mention anything about my problem
- [X] There are no open or closed issues that are related to my problem

### Description

I'm trying to use this action to build a multi stage image using a docker compose configuration file. The build is working correctly and the images are pushed to the Google Artifacts registry just fine, but subsequent builds are not taking advantage of the layers cache even though nothing in the repository changed at all.

<img width="655" alt="Screenshot 2024-09-01 at 19 07 08" src="https://github.com/user-attachments/assets/9fb3de86-6490-4a8a-b85d-aac42444921a">

### Expected behaviour

I would expect this to be way higher than 0%

### Actual behaviour

Cache seem not to be used at all?

### YAML workflow

```yaml
# Setup gcloud CLI
      - uses: "google-github-actions/setup-gcloud@v2"
        if: ${{ env.dryRun == 'false' }}
        with:
          project_id: ${{ env.GCP_PROJECT_ID }}
          version: "482.0.0"

      # This gives us access to buildx
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3

      # Configure Docker to use the gcloud command-line tool as a credential
      # helper for authentication
      - if: ${{ env.dryRun == 'false' }}
        run: |-
          gcloud --quiet auth configure-docker

      # Get the GKE credentials so we can deploy to the cluster
      - uses: google-github-actions/get-gke-credentials@db150f2cc60d1716e61922b832eae71d2a45938f
        if: ${{ env.dryRun == 'false' }}
        with:
          cluster_name: ${{ env.GKE_CLUSTER }}
          location: ${{ env.GCP_LOCATION }}

      - name: Build and Push Docker Images
        uses: docker/bake-action@v5
        env:
          TAG: ${{ steps.release-tag.outputs.tag }}
        with:
          source: "."
          files: "compose.yaml"
          workdir: "./docker"
          push: ${{ env.dryRun == 'false' }}
          load: true
```

**Comment by crazy-max** [comment]
> but subsequent builds are not taking advantage of the layers cache even though nothing in the repository changed at all.

I don't see any use of cache exporters in your workflow. You can use the gha exporter for example:

```yaml
      - name: Build and Push Docker Images
        uses: docker/bake-action@v5
        env:
          TAG: ${{ steps.release-tag.outputs.tag }}
        with:
          source: "."
          files: "compose.yaml"
          workdir: "./docker"
          push: ${{ env.dryRun == 'false' }}
          load: true
          set:
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
```

More info: https://docs.docker.com/build/ci/github-actions/cache/

**Comment by FezVrasta** [comment]
Thanks, that helped, but still I see only ~60% caching on runs where nothing in the repository changed at all 🤔

PACKAGES_TO_INSTALL

**Comment by FezVrasta** [comment]
Thanks for the help, this is my [Dockerfile](https://gist.github.com/FezVrasta/191d202b3a30b3c6ebfa95b181864687) and this the .dockerbuild:
[dockerbuild.zip](https://github.com/user-attachments/files/16837222/dockerbuild.zip)

Personally I don't see anything that could result in cache invalidation.

**Comment by crazy-max** [comment]
Seems cache is busted at `COPY --parents` instruction:

![image](https://github.com/user-attachments/assets/43a77e86-9f0b-4edd-98ae-281f68aba0ba)

Wonder if this is a bug with new `--parents` flag :thinking:

Can you try without `--parents` if possible?

Can you also change this step:

```yaml
      # This gives us access to buildx
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
```

to

```yaml

      # This gives us access to buildx
      - name: Set up Docker CLI
        uses: docker/setup-buildx-action@v3
        with:
          buildkitd-flags: --debug
```

And post the BuildKit logs from post step: https://docs.docker.com/build/ci/github-actions/configure-builder/#buildkit-container-logs
