### ISSUE TITLE
Allow Network Host

### ISSUE THREAD

**Issue by fnacarellidev** [docker/bake-action#252]
### Description

Is there any way to specify the `--allow=network.host` flag to bake without manually running the command? I tried using the `entitlements` field, but it didn't work, didn't find anything other than that that seems to be related with the problem I'm having:

![image](https://github.com/user-attachments/assets/10a58f97-77d3-4434-aec0-2580a9944a3f)

**Comment by crazy-max** [comment]
Can you create a [bug report](https://github.com/docker/bake-action/issues/new?assignees=&labels=status%2Ftriage&projects=&template=bug.yml) and provide a link to your repo or give us a small repro please?

**Comment by crazy-max** [comment]
> @crazy-max thank you for the fast reply. Do you know if there's a way to pass this `--allow=network.host` through the bake yml?

You can't enforce within the bake definition but you can with `--allow` flag in bake but we need to add this input to this action sorry for this oversight!

**Comment by fnacarellidev** [comment]
Maybe add an option like `buildkitd-flags` on https://github.com/docker/setup-buildx-action?tab=readme-ov-file#customizing, I think that would solve the issue, wouldn't it?

**Comment by crazy-max** [comment]
> Ah I see, so that's not available yet, I look forward into contributing to open-source projects, do you think it would be too hard to implement that? If you can maybe assist me I would like to try :)

Thanks but already opened one https://github.com/docker/bake-action/pull/253 sorry :sweat_smile:

> Maybe add an option like `buildkitd-flags` on https://github.com/docker/setup-buildx-action?tab=readme-ov-file#customizing, I think that would solve the issue, wouldn't it?

No, the inputs action should have the same UX as the `bake` command, see https://docs.docker.com/reference/cli/docker/buildx/bake/. In this case we need an `allow` input.

**Comment by crazy-max** [comment]
@fnacarellidev Btw can you create a repro for your issue or share your bake definition?

**Comment by fnacarellidev** [comment]
Sure, this is my current bake definition:
```yml
- name: bake integrate
        uses: docker/bake-action@v5
        with:
          push: false
          load: true
          targets: integrate
          workdir: ${{ matrix.package }}
          files: |-
            compose.yaml
            compose-cache.json
```

compose.yml:
```yml
services:
  integrate:
    command: "true"
    build:
      context: ../..
      dockerfile: svcs/books/Dockerfile
      network: host
      target: integrate
```

compose-cache.json:
```json
{
    "target": {
      "integrate": {
        "cache-from": [
          "type=gha,scope=ci-Linux-X64-devserver",
          "type=gha,scope=ci-Linux-X64-svcs-books-integrate"
        ],
        "cache-to": [
          "type=gha,scope=ci-Linux-X64-svcs-books-integrate"
        ],
        "output": [
          "type=docker"
        ]
      }
   }
}

```
