### ISSUE TITLE
V6 broke interaction with docker/metadata-action

### ISSUE THREAD

**Issue by davhdavh** [docker/bake-action#287]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

existing build scripts using docker/metadata-action are failing with v6 due to confusion about where the files are located

### Expected behaviour

build success

### Actual behaviour

ERROR: failed to solve: lstat /actions-runner/_work/_temp/docker-actions-toolkit-YZDiwT/docker-metadata-action-bake.json: no such file or directory

### YAML workflow

```yaml
- name: Docker meta
      id: meta-yyy
      uses: docker/metadata-action@369eb591f429131d6889c46b94e711f089e6ca96 # v5
      with:
        images: |
          ${{ secrets.DOCKER_USERNAME }}/xxx
        flavor: |
          latest=false
          prefix=yyy-
        tags: |
          type=raw,value=${{ github.run_number }}
        labels: |
          org.opencontainers.image.title=xxx
          org.opencontainers.image.description=xxx
          org.opencontainers.image.vendor=xxx
        bake-target: yyy-tags

    - name: Build
      uses: docker/bake-action@60f5d53310314dbf8c33f0c8a01042536f2f6c36 # v6
      with:
        files: |
          ./docker-bake.json
          ${{ steps.meta-yyy.outputs.bake-file }}
        targets: default
        push: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate') }}
        pull: true #always pull latest version of base images of whatever we are building
```

### BuildKit logs

```text

```

**Comment by crazy-max** [comment]
As v6 is now using Git context by default (https://github.com/docker/bake-action/releases/tag/v6.0.0), it needs some changes in the metadata-action step: https://github.com/docker/metadata-action?tab=readme-ov-file#bake-definition

You needs to use the local bake file by specifying the `cwd://` prefix when building with a git context, otherwise it will try to look at this file within the git repo.

In your case:

```yaml
    - name: Build
      uses: docker/bake-action@60f5d53310314dbf8c33f0c8a01042536f2f6c36 # v6
      with:
        files: |
          ./docker-bake.json
          cwd://${{ steps.meta-yyy.outputs.bake-file }}
        targets: default
        push: ${{ github.event_name != 'pull_request' || !startsWith(github.head_ref, 'renovate') }}
        pull: true #always pull latest version of base images of whatever we are building
```

More info: https://docs.docker.com/build/bake/remote-definition/#combine-local-and-remote-bake-definitions
