### ISSUE TITLE
Using set overides rather than merges with array settings in docker-bake.hcl

### ISSUE THREAD

**Issue by ncrmro** [docker/bake-action#295]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

It appears target sets are not merged with existing array and instead overide settings in the bake file.

Specifically `cache-from`'s set in the action's `set` are not merged with cache froms in the the bake file

### Expected behaviour

Given a `docker-bake.hcl`
```
target "foobar" {
  context = "."
  dockerfile = "Dockerfile"
  cache-release-from = [
    "type=registry,ref=ghcr.io/exampeorg/foobar:cache-release-development-staging"
  ]
}
```

And an action that sets cache-from, cache-to
```
      - name: Build and cache foobartarget
        uses: docker/bake-action@v6
        with:
          source: .
          targets: foobar
          files: docker-bake.hcl
          set: |
           foobar.cache-from=type=registry,ref=gghcr.io/exampeorg/foobar:cache-pr-development-PR-0000
            foobar.cache-to=type=registry,ref=ghcr.io/exampeorg/foobar:cache-pr-development-PR-0000,mode=max
```

Will result in a bake definition

```
  {
    "group": {
      "default": {
        "targets": [
          "foobar"
        ]
      }
    },
    "target": {
      "foobar": {
        "attest": [
          {
            "type": "provenance"
          }
        ],
        "context": ".",
        "dockerfile": "Dockerfile",
        "cache-from": [
          {
            "ref": "ghcr.io/exampeorg/foobar:cache-release-development-staging",
            "type": "registry"
          },
          {
            "ref": "ghcr.io/exampeorg/foobar:cache-pr-development-PR-0000",
            "type": "registry"
          }
        ],
        "cache-to": [
          {
            "mode": "max",
            "ref": "ghcr.io/exampeorg/foobar:cache-pr-development-PR-0000",
            "type": "registry"
          }
        ],
        "target": "foobar"
      }
    }
  }
```

### Actual behaviour

I would expect this to merge and result in.

```
  {
    "group": {
      "default": {
        "targets": [
          "foobar"
        ]
      }
    },
    "target": {
      "foobar": {
        "attest": [
          {
            "type": "provenance"
          }
        ],
        "context": ".",
        "dockerfile": "Dockerfile",
        "cache-from": [
          {
            "ref": "ghcr.io/exampeorg/foobar:cache-pr-development-PR-0000",
            "type": "registry"
          }
        ],
        "cache-to": [
          {
            "mode": "max",
            "ref": "ghcr.io/exampeorg/foobar:cache-pr-development-PR-0000",
            "type": "registry"
          }
        ],
        "target": "foobar"
      }
    }
  }
```
```

### Repository URL

_No response_

### Workflow run URL

_No response_

### YAML workflow

```yaml
See expected behavor.
```

### BuildKit logs

```text

```
