### ISSUE TITLE
Build summary does not include images created with matrix

### ISSUE THREAD

**Issue by betelgeuse** [docker/bake-action#299]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I have a bake configuration that uses matrix:

```hcl
target "foo1" {
  matrix {
    VAR = ["a", "b", "c"]
  }
}

target "foo2" {
}
```

### Expected behaviour

Build summary includes foo1 images

### Actual behaviour

Build summary only includes foo2 image

### YAML workflow

```yaml
- name: Build and push
        uses: docker/bake-action@v6
        with:
          source: .
          provenance: false
          targets: foo1,foo2
```

### BuildKit logs

```text

```
