### ISSUE TITLE
Bad context on version 6.x.x

### ISSUE THREAD

**Issue by 76creates** [docker/bake-action#301]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I have GH action where I update the `.npmrc` file to include authentication, this file is existing prior to me updating it and it contains placeholder info.

Example:
original `. npmrc`
```
foo:=_authToken=
```
updated `. npmrc` in step prior to build
```
foo:=_authToken=123
```

When I run build with `.` as a context, and use `COPY . .` the contents of the `.npmrc` within a build is original file as opposed to updated one.

Since I have used `@master` Ive tried with `@v6.3.0` and `@v5.13.0`, it fails on `6` and passes with `5` version.

### Expected behaviour

`.npmrc` contents are: 
```
foo:=_authToken=123
```

### Actual behaviour

`.npmrc` contents are: 
```
foo:=_authToken=
```

### YAML workflow

```yaml
...
      - name: Update npmrc
        run: echo '//npm.pkg.github.com:_authToken=${{ secrets.GHRC_REPO_TOKEN }}' > .npmrc

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHRC_REPO_TOKEN }}

      - name: Build and push
        env:
          IMAGE: ${{ env.IMAGE_NAME }}
          REPO: ${{ github.repository }}
          TAG: ${{ needs.opts.outputs.tag }}
          META_TAG: ${{ needs.opts.outputs.metaTag }}
        uses: docker/bake-action@v6.3.0
        with:
          targets: default
          push: false
...
```

### BuildKit logs

```text

```

### Additional info

```
FROM node:18.20.4-alpine As builder

WORKDIR /app
COPY . .

# added to debug the issue
RUN cat .npmrc

RUN npm ci
RUN npm run build
RUN rm .npmrc

EXPOSE 3000
CMD [ "npm", "start" ]

```
