### ISSUE TITLE
unknown cache exporter

### ISSUE THREAD

**Issue by cortopy** [docker/bake-action#306]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

I'm running bake-action like this:

```yaml
     - name: Build and push
        uses: docker/bake-action@v6
        env:
          versions_string: ${{ steps.short-sha.outputs.sha }},latest
        with:
          push: true
          files: |
            ./${{ matrix.package.directory }}/docker-bake.hcl
          set: |
            *.cache-from="type=gha"
            *.cache-to="type=gha,mode=max"
```

and I'm getting error:

```
ERROR: failed to solve: unknown cache exporter: "gha,mode=max"
```

I've searched for other issues in the repo, and my configuration matches what others have said in the past should work I think

### Expected behaviour

Action uses `gha` docker cache

### Actual behaviour

Image doesn't build due to error

### YAML workflow

```yaml
name: Development Build

on:
  push:
    branches:
      - development

jobs:
  determine-apps-affected:
    # ....
          

  build_image:
    runs-on: ubuntu-22.04
    needs: [determine-apps-affected]
    strategy:
      matrix:
        package: ${{ fromJson(needs.determine-apps-affected.outputs.matrix) }}
    steps:
      - uses: benjlevesque/short-sha@v3.0
        id: short-sha
        with:
          length: 6

      - name: Login to container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ VARS.CONTAINER_REGISTRY }}
          username: ${{ vars.CONTAINER_REGISTRY_USERNAME }}
          password: ${{ secrets.CONTAINER_REGISTRY_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          versions_string: ${{ steps.short-sha.outputs.sha }},latest
        with:
          push: true
          files: |
            ./${{ matrix.package.directory }}/docker-bake.hcl
          set: |
            *.cache-from="type=gha"
            *.cache-to="type=gha,mode=max"
```

### BuildKit logs

```text

```
