### ISSUE TITLE
Ability to set variables values for bake files

### ISSUE THREAD

**Issue by garry-t** [docker/bake-action#309]
### Description

Currently I dont see option to set variable values for bake files. 

How to set value for test? 

```
variable "TEST" {
  default = "false"
}

group "default" {
  targets = ["test-ci"]
}

target "test-ci" {
  context = "components/test/container/test"
  dockerfile = "Dockerfile"
  tags = [
    "ghcr.io/me/citest:latest",
    notequal(TEST, "true") ? "" : "ghcr.io/me/citest:test"
  ]

  cache-to = ["type=gha,mode=max"]
  cache-from = ["type=gha"]

  labels = {
    "version"       = "1.0.0"
    "description"   = "Simple Docker image for CI testing"
  }
  platforms = ["linux/amd64"]
}
```
Currently I build it like 
```TEST=true docker buildx bake --file components/test/container/test/docker-bake.hcl --load```

**Comment by crazy-max** [comment]
In GitHub Actions you can use the `env` object to set your variable like:

```yaml
      -
        name: Build
        uses: docker/bake-action@v6
        with:
          files: components/test/container/test/docker-bake.hcl
          load: true
        env:
          TEST: true
```
