### ISSUE TITLE
Since v6, docker compose up is crashing

### ISSUE THREAD

**Issue by tidall87** [docker/bake-action#311]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

When I push my CI is always failing since I passed to bake-action@v6. With bake-action@v5 all is good.

### Expected behaviour

After building images i need to start them to the nest steps for tests.

### Actual behaviour

With v5 docker compose up is working well.
With v6 docker compose up is not working. The error is:

```
Run docker compose up --wait --no-build
  docker compose up --wait --no-build
  shell: /usr/bin/bash -e {0}
no configuration file provided: not found
Error: Process completed with exit code 1[4](https://github.com/tidall87/cine-media-display/actions/runs/13950174078/job/39047333040#step:4:5).
```

### Repository URL

https://github.com/tidall87/cine-media-display

### Workflow run URL

https://github.com/tidall87/cine-media-display/actions/runs/13950174078

### YAML workflow

```yaml
name: CI

on:
  push:
  pull_request: ~
  workflow_dispatch: ~

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    steps:
#      - name: Checkout
#        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      - name: Start services
        run: docker compose up --wait --no-build
      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
  lint:
    name: Docker Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Lint Dockerfiles
        uses: hadolint/hadolint-action@v3.1.0
        with:
          recursive: true
```

### BuildKit logs

```text

```

**Comment by crazy-max** [comment]
> Run docker compose up --wait --no-build
>   docker compose up --wait --no-build
>   shell: /usr/bin/bash -e {0}
> no configuration file provided: not found

That's because your compose file is not available as you're not checking out your repo anymore. In such case you should keep the Checkout step and use the [path context](https://github.com/docker/bake-action?tab=readme-ov-file#path-context):

```yaml
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build Docker images
        uses: docker/bake-action@v6
        with:
          source: .
          pull: true
          load: true
          files: |
            compose.yaml
            compose.override.yaml
          set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
      - name: Start services
        run: docker compose up --wait --no-build
      - name: Check HTTP reachability
        run: curl -v --fail-with-body http://localhost
```
