### ISSUE TITLE
Error writing to cache: 404 The specified blob does not exist

### ISSUE THREAD

**Issue by darthmaim** [docker/bake-action#313]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

During the past few weeks my ` docker/bake-action` steps regularly fail while writing to the cache.

### Expected behaviour

This used to always work.

### Actual behaviour

The ` docker/bake-action` step sometimes fails while writing to the cache. Rerunning the job usually fixes this.

### Repository URL

https://github.com/GW2Treasures/gw2.me

### Workflow run URL

https://github.com/GW2Treasures/gw2.me/actions/runs/14018358983/job/39246950494

### YAML workflow

```yaml
- name: Build the Docker image
      uses: docker/bake-action@v6.5.0
      with:
        source: .
        files: ./docker-compose.yml
        targets: ${{ matrix.target }}
        set: |
          ${{ matrix.target }}.output=type=image,push=true
          *.platform=linux/amd64,linux/arm64
          *.cache-from=type=gha,scope=build-${{ matrix.target }}
          *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max
```

### Workflow logs

```raw
#35 exporting to GitHub Actions Cache
#35 preparing build cache for export
#35 writing layer sha256:19f059763ac032d8a4628ae8713506e801b2221624dc127e44946545a4299a3b
#35 preparing build cache for export 0.6s done
#35 writing layer sha256:19f059763ac032d8a4628ae8713506e801b2221624dc127e44946545a4299a3b 0.3s done
#35 ERROR: error writing layer blob: GET https://productionresultssa7.blob.core.windows.net/actions-cache/ecf-107766243
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified blob does not exist.
ERROR CODE: BlobNotFound
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:95d77998-e01e-00c7-46e4-9b8256000000
Time:2025-03-23T11:09:12.8776564Z</Message></Error>
--------------------------------------------------------------------------------

------
 > exporting to GitHub Actions Cache:
------
WARNING: : the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
WARNING: ./docker-compose.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
ERROR: failed to solve: error writing layer blob: GET https://productionresultssa7.blob.core.windows.net/actions-cache/ecf-107766243
--------------------------------------------------------------------------------
RESPONSE 404: 404 The specified blob does not exist.
ERROR CODE: BlobNotFound
--------------------------------------------------------------------------------
﻿<?xml version="1.0" encoding="utf-8"?><Error><Code>BlobNotFound</Code><Message>The specified blob does not exist.
RequestId:95d77998-e01e-00c7-46e4-9b8256000000
Time:2025-03-23T11:09:12.8776564Z</Message></Error>
--------------------------------------------------------------------------------
```

### BuildKit logs

```text

```

### Additional info

In https://github.com/actions/cache/issues/1541#issuecomment-2651968376 a staff member wrote:
> On February 7th we began the rollout of the new cache service backend.

This date roughly aligns with when I started seeing these issues. Maybe some dependency has to be updated?

I have this issue in multiple repositories, just reported the only with the simplest workflow setup.

#312 is similar, but failing with a 403 instead of a 404, which I haven't observed yet.

**Comment by crazy-max** [comment]
Seems to be an issue on GitHub side, we can't do much about it unfortunately but will report this to GitHub staff. In the meantime you can set `ignore-error=true` to ignore the error in case cache export fails:

```yaml
- name: Build the Docker image
  uses: docker/bake-action@v6.5.0
  with:
    source: .
    files: ./docker-compose.yml
    targets: ${{ matrix.target }}
    set: |
      ${{ matrix.target }}.output=type=image,push=true
      *.platform=linux/amd64,linux/arm64
      *.cache-from=type=gha,scope=build-${{ matrix.target }}
      *.cache-to=type=gha,scope=build-${{ matrix.target }},mode=max,ignore-error=true
```
