### ISSUE TITLE
manifest gets written over not appended

### ISSUE THREAD

**Issue by magick93** [docker/bake-action#314]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

And I am expecting that the manifest would show two platforms once the build has completed. 

Instead I'm getting one, the other us `unknown`, and it depends on the order of completion, indicating the manifest is not updated but is being written over. 

### Expected behaviour

I am expecting the manifest to contain the list of platforms specified in the bake file

### Actual behaviour

# Example Manifest 
This is the generated manifest
```json
{
   "schemaVersion": 2,
   "mediaType": "application/vnd.oci.image.index.v1+json",
   "manifests": [
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 867,
         "digest": "sha256:c8dd61c4aae7871f838502de9e33b24c5605c46ec05e881ebc2f8878c748e27c",
         "platform": {
            "architecture": "amd64",
            "os": "linux"
         }
      },
      {
         "mediaType": "application/vnd.oci.image.manifest.v1+json",
         "size": 566,
         "digest": "sha256:1970fd1283eda92c96c74ba084fcf97af20af99be70b24bb25100fc63e18f206",
         "platform": {
            "architecture": "unknown",
            "os": "unknown"
         }
      }
   ]
}
```

### YAML workflow

```yaml
name: docker

on:
  push:
    branches:
    - main
    - stable
    - unstable

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
    DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
    DOCKER_BUILD_SUMMARY: true

jobs:
    build-docker-single-arch:
        name: build-docker-${{ matrix.cpu_arch }}
        runs-on: ubuntu-22.04
        strategy:
          fail-fast: false
          matrix:
            cpu_arch: [aarch64, x86_64]
        steps:

            - uses: actions/checkout@v4
            - name: Update Rust
              run: rustup update stable
            - name: Login to DockerHub
              uses: docker/login-action@v3
              with:
                username: ${{ env.DOCKER_USERNAME }}
                password: ${{ env.DOCKER_PASSWORD }}
                
            - name: Cross build binaries
              run: |
                  cargo install cross
                  make build-${{ matrix.cpu_arch }}
              timeout-minutes: 100

            - name: Make bin dir
              run: mkdir ./bin

            - name: Move cross-built binary into Docker scope
              run: mv ./target/${{ matrix.cpu_arch }}-unknown-linux-gnu/release/eleel ./bin/eleel

            - name: Map aarch64 to arm64 short arch
              if: startsWith(matrix.cpu_arch, 'aarch64')
              run: echo "SHORT_ARCH=arm64" >> $GITHUB_ENV

            - name: Map x86_64 to amd64 short arch
              if: ${{ matrix.cpu_arch == 'x86_64' }}
              run: echo "SHORT_ARCH=amd64" >> $GITHUB_ENV

            - name: Install QEMU
              run: sudo apt-get update && sudo apt-get install -y qemu-user-static

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Build and push using Bake
              uses: docker/bake-action@v6
              with:
                files: ./docker-bake.hcl
                source: .
                push: true
                set: |
                  *.context=.
                  *.tags=${{ github.repository_owner }}/${{ github.repository_name }}:${{ github.ref_name }}
              env:
                  ARCH: ${{ env.SHORT_ARCH }}
                  GITHUB_REPO: ${{ github.repository_owner }}/${{ github.repository_name }}
                  DOCKER_BUILD_RECORD_UPLOAD: true
```

### BuildKit logs

```text

```
