### ISSUE TITLE
When using `setup-buildx-action` images aren't loaded to local

### ISSUE THREAD

**Issue by onedr0p** [docker/bake-action#315]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

When using the `setup-buildx-action` and this docker bake action images aren't loaded locally. However when I remove the `setup-buildx-action` step, they are.

### Expected behaviour

Using `setup-buildx-action`and this docker bake action the image should be loaded locally.

### Actual behaviour

I am unable to reference a local docker image after it was built with docker bake.

### Repository URL

https://github.com/home-operations/containers/tree/baking-goodies

### Workflow run URL

https://github.com/home-operations/containers/actions/runs/14121503439

### YAML workflow
https://github.com/home-operations/containers/blob/a5a43107ac70168fe9cb94da4bcb84267e862a37/.github/workflows/image-build-action.yaml#L124

```yaml
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3.10.0
        id: buildx

      - name: Build
        uses: docker/bake-action@4ba453fbc2db7735392b93edf935aaf9b1e8f747 # v6.5.0
        id: bake
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          load: true
          set: |
            *.args.VENDOR=${{ steps.vars.outputs.repository-owner }}
            *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) }}
            *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2}', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) || '' }}
            *.labels.org.opencontainers.image.title=${{ inputs.app }}
            *.labels.org.opencontainers.image.url=https://ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ inputs.app }}
            *.labels.org.opencontainers.image.version=${{ steps.bake-version.outputs.version }}
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.labels.org.opencontainers.image.vendor=${{ steps.vars.outputs.repository-owner }}
            ${{ inputs.release && format('*.output=type=image,name=ghcr.io/{0}/{1},push-by-digest=true,name-canonical=true,push=true', steps.vars.outputs.repository-owner, inputs.app) || '' }}
            *.platform=${{ matrix.platform }}
            *.tags=
          source: .
          targets: image
          workdir: ./apps/${{ inputs.app }}

      - if: ${{ inputs.test }}
        name: Run Container Tests
        uses: ./.github/actions/container-tests
        with:
          app: ${{ inputs.app }}
          image: ${{ fromJSON(steps.bake.outputs.metadata).image['containerimage.digest'] }}
          token: ${{ github.token }}
```

### BuildKit logs

```text

```

### Additional info

```hcl
target "docker-metadata-action" {}

variable "VERSION" {
  // renovate: datasource=github-releases depName=Jackett/Jackett
  default = "v0.22.1699"
}

group "default" {
  targets = ["image-local"]
}

target "image" {
  inherits = ["docker-metadata-action"]
  args = {
    VERSION = "${VERSION}"
  }
  labels = {
    "org.opencontainers.image.source" = "https://github.com/Jackett/Jackett"
  }
}

target "image-local" {
  inherits = ["image"]
  output = ["type=docker"]
}

target "image-all" {
  inherits = ["image"]
  platforms = [
    "linux/amd64",
    "linux/arm64"
  ]
}
```

**Comment by onedr0p** [comment]
Now here's the run where I removed the setup-buildx-setup step and it works. 

https://github.com/home-operations/containers/actions/runs/14121383606

**Comment by crazy-max** [comment]
> When using the `setup-buildx-action` and this docker bake action images aren't loaded locally.

`setup-buildx-action` will create and boot a builder using the [`docker-container` driver](https://docs.docker.com/build/building/drivers/docker-container/) but this driver does not load the image to the docker store by default.

I see you set `load: true` so it should load to the docker store: https://github.com/home-operations/containers/actions/runs/14121503439/job/39562491996#step:8:284

Can you add the following step right after the `Build` one to check the image is there?

```yaml
- name: Check image
  run: |
    docker image ls -a
```

**Comment by onedr0p** [comment]
I already tried that, my workflow history is riddled with debugging attempts to see what's going on 

https://github.com/home-operations/containers/actions/runs/14121357107/job/39562097543

**Comment by onedr0p** [comment]
Here the run with the exact commands you wanted:

https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266

**Comment by onedr0p** [comment]
I thought something in the set option could be triggering the failure so I tried this, but no luck:

```yaml
          set: |
            *.platform=${{ matrix.platform }}
            *.tags=
          # set: |
          #   *.args.VENDOR=${{ steps.vars.outputs.repository-owner }}
          #   *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) }}
          #   *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2}', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) || '' }}
          #   *.labels.org.opencontainers.image.title=${{ inputs.app }}
          #   *.labels.org.opencontainers.image.url=https://ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ inputs.app }}
          #   *.labels.org.opencontainers.image.version=${{ needs.prepare.outputs.bake-version }}
          #   *.labels.org.opencontainers.image.revision=${{ github.sha }}
          #   *.labels.org.opencontainers.image.vendor=${{ steps.vars.outputs.repository-owner }}
          #   ${{ inputs.release && format('*.output=type=image,name=ghcr.io/{0}/{1},push-by-digest=true,name-canonical=true,push=true', steps.vars.outputs.repository-owner, inputs.app) || '' }}
          #   *.platform=${{ matrix.platform }}
          #   *.tags=
```

**Comment by crazy-max** [comment]
> Here the run with the exact commands you wanted:
> 
> https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266

Ok I think I understand. The digest you try to use in this run: https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266#step:9:11

```
+ docker image inspect sha256:a15c6e566fd23c2041f300baf614eaadd8950371f437b3cc957f4054e63e550a
```

Is the one from `containerimage.digest` in the metadata: https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266#step:8:429

But looking at `docker image ls` output: https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266#step:9:7

```
 + docker image ls -a
REPOSITORY      TAG               IMAGE ID       CREATED      SIZE
moby/buildkit   buildx-stable-1   3c2d38015344   3 days ago   209MB
<none>          <none>            7ca50b5a2c04   9 days ago   178MB
```

You need to use `containerimage.config.digest`: https://github.com/home-operations/containers/actions/runs/14127276999/job/39579084432?pr=266#step:8:416

More info on difference between both digests in https://github.com/docker/build-push-action/issues/770#issuecomment-1410915617.

Can you try with:

```yaml
- name: Check image
  run: |
    set -ex
    docker image ls -a
    docker image inspect ${{ fromJSON(steps.bake.outputs.metadata).image['containerimage.config.digest'] }}
```

**Comment by crazy-max** [comment]
Also it would be easier if you just tag your image tbh:

```yaml
      - name: Build
        uses: docker/bake-action@4ba453fbc2db7735392b93edf935aaf9b1e8f747 # v6.5.0
        id: bake
        with:
          builder: ${{ steps.buildx.outputs.name }}
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          load: true
          set: |
            *.args.VENDOR=${{ steps.vars.outputs.repository-owner }}
            *.cache-from=${{ format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2},mode=max', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) }}
            *.cache-to=${{ inputs.release && format('type=registry,ref=ghcr.io/{0}/build_cache:{1}-{2}', steps.vars.outputs.repository-owner, inputs.app, steps.vars.outputs.platform-arch) || '' }}
            *.labels.org.opencontainers.image.title=${{ inputs.app }}
            *.labels.org.opencontainers.image.url=https://ghcr.io/${{ steps.vars.outputs.repository-owner }}/${{ inputs.app }}
            *.labels.org.opencontainers.image.version=${{ steps.bake-version.outputs.version }}
            *.labels.org.opencontainers.image.revision=${{ github.sha }}
            *.labels.org.opencontainers.image.vendor=${{ steps.vars.outputs.repository-owner }}
            ${{ inputs.release && format('*.output=type=image,name=ghcr.io/{0}/{1},push-by-digest=true,name-canonical=true,push=true', steps.vars.outputs.repository-owner, inputs.app) || '' }}
            *.platform=${{ matrix.platform }}
            *.tags=foo/bar:latest
          source: .
          targets: image
          workdir: ./apps/${{ inputs.app }}

      - if: ${{ inputs.test }}
        name: Run Container Tests
        uses: ./.github/actions/container-tests
        with:
          app: ${{ inputs.app }}
          image: foo/bar:latest
          token: ${{ github.token }}
```
