### ISSUE TITLE
Github Cache not working anymore: This legacy service is shutting down, effective April 15, 2025. Migrate to the new service ASAP.

### ISSUE THREAD

**Issue by arjendevos** [docker/bake-action#324]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [ ] The documentation does not mention anything about my problem
- [ ] There are no open or closed issues that are related to my problem

### Description

I'm using the cache like this:

```
set: |
    *.cache-from=type=gha
    *.cache-to=type=gha,mode=max
```

But github deprecated the old cache on april 15 2025. 

### Expected behaviour

Cache should work.

### Actual behaviour

Cache is deprecated.

### YAML workflow

```yaml
- name: Build and push images using Docker Bake
    uses: docker/bake-action@v6.5.0
    env:
        DOCKER_BUILD_RECORD_UPLOAD: false
    with: 
        source: .
        files: docker-compose.${{ inputs.environment }}.yaml
        load: true
        set: |
            *.cache-from=type=gha,scope=${{github.ref}}
            *.cache-from=type=gha,scope=refs/heads/main
            *.cache-to=type=gha,scope=${{github.ref}},mode=max
```

### BuildKit logs

```text

```
