### ISSUE TITLE
When building in parallel using multiple GitHub Actions runners, the cache generated by the last runner will overwrite the caches produced by the previous runners, resulting in only a single architecture's cache being available for subsequent builds.

### ISSUE THREAD

**Issue by vivodi** [docker/bake-action#329]
### Contributing guidelines

- [x] I've read the [contributing guidelines](https://github.com/docker/bake-action/blob/master/.github/CONTRIBUTING.md) and wholeheartedly agree

### I've found a bug, and:

- [x] The documentation does not mention anything about my problem
- [x] There are no open or closed issues that are related to my problem

### Description

When building a multi-platform image in parallel using multiple GitHub Actions runners, **the cache generated by the last runner will overwrite the caches produced by the previous runners**, resulting in only a single architecture's cache being available for subsequent builds.

You can observe from my multiple executions of the same workflow run that each time, only one architecture was able to utilize the cache.
https://github.com/vivodi/Flexget/actions/runs/14690915690
![Image](https://github.com/user-attachments/assets/a4bc9d97-936e-4fe8-9e71-921f42df4359)

### Expected behaviour

When using multiple runners to build multi-platform images in parallel, the caches for different architectures can coexist harmoniously without conflicts.

### Actual behaviour

Only the cache corresponding to the architecture that completes its build last will be retained._

### Repository URL

https://github.com/vivodi/Flexget

### Workflow run URL

https://github.com/vivodi/Flexget/actions/runs/14690915690

### YAML workflow

```yaml
name: Docker Image CI

on:
  push:
    branches:
      - develop
    tags:
      - v*.*.*
  pull_request:
  merge_group:
permissions: { }
concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref || github.run_id }}
  cancel-in-progress: true
env:
  REGISTRY_IMAGE: ${{ vars.DOCKER_IMAGE_NAMESPACE }}/flexget
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/flexget
jobs:
  build:
    name: Docker build
    runs-on: ${{ matrix.operating-system }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: linux/amd64
            operating-system: ubuntu-latest
          - platform: linux/arm64
            operating-system: ubuntu-24.04-arm
    steps:
      - name: Prepare
        run: |
          platform=${{ matrix.platform }}
          echo PLATFORM_PAIR=${platform//\//-} >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@902fa8ec7d6ecbf8d84d538b9b233a880e428804 # v5
        with:
          images: |
            ${{ env.REGISTRY_IMAGE }}
            ${{ env.GHCR_IMAGE }}
          tags: |
            type=ref,event=branch
            type=pep440,pattern={{version}}
            type=pep440,pattern={{major}}.{{minor}}
            type=pep440,pattern={{major}}

      - name: Rename meta bake definition file
        run: |
          mv ${{ steps.meta.outputs.bake-file }} ${{ runner.temp }}/bake-meta.json

      - name: Upload meta bake definition
        if: matrix.platform == 'linux/amd64'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}/bake-meta.json
          if-no-files-found: error
          retention-days: 1

      - name: Login to Docker Hub
        if: github.event_name == 'push'
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3 # zizmor: ignore[cache-poisoning]

      - name: Build
        id: bake
        uses: docker/bake-action@76f9fa3a758507623da19f6092dc4089a7e61592 # v6
        with:
          files: |
            ./docker-bake.hcl
            cwd://${{ runner.temp }}/bake-meta.json
          targets: all
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
            *.tags=
            *.platform=${{ matrix.platform }}
            *.output=type=image,name=${{ env.REGISTRY_IMAGE }},push-by-digest=true,push=${{github.event_name == 'push'}}

      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests
          digest="${{ fromJSON(steps.bake.outputs.metadata).all['containerimage.digest'] }}"
          touch "${{ runner.temp }}/digests/${digest#sha256:}"

      - name: Upload digest
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: digests-${{ env.PLATFORM_PAIR }}
          path: ${{ runner.temp }}/digests/*
          if-no-files-found: error
          retention-days: 1

  merge:
    if: github.event_name == 'push'
    needs:
      - build
    runs-on: ubuntu-latest
    permissions:
      packages: write # to push to ghcr.io
    steps:
      - name: Download meta bake definition
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          name: bake-meta
          path: ${{ runner.temp }}

      - name: Download digests
        uses: actions/download-artifact@95815c38cf2ff2164869cbab79da8d1f422bc89e # v4
        with:
          path: ${{ runner.temp }}/digests
          pattern: digests-*
          merge-multiple: true

      - name: Log in to Docker Hub
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Login to GitHub Container Registry
        uses: docker/login-action@74a5d142397b4f367a81961eba4e8cd7edddf772 # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@b5ca514318bd6ebac0fb2aedd5d36ec1b5c232a2 # v3 # zizmor: ignore[cache-poisoning]

      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests
        run: |
          docker buildx imagetools create $(jq -cr '.target."docker-metadata-action".tags |
            map(select(startswith("${{ env.REGISTRY_IMAGE }}") or startswith("${{ env.GHCR_IMAGE }}")) | "-t " + .) |
            join(" ")' ${{ runner.temp }}/bake-meta.json) $(printf '${{ env.REGISTRY_IMAGE }}@sha256:%s ' *)
```

### Workflow logs

#21 exporting to GitHub Actions Cache
#21 preparing build cache for export
#21 writing layer sha256:5f7b94875ec3e07a6edddcb16369b4ecd4c76e47b1aa1535182726e33693441c
#21 writing layer sha256:5f7b94875ec3e07a6edddcb16369b4ecd4c76e47b1aa1535182726e33693441c 0.5s done
#21 writing layer sha256:638571e5299939a9cd696c1e77100756662d1336449cc72ad67bff7a532a2f53
#21 writing layer sha256:638571e5299939a9cd696c1e77100756662d1336449cc72ad67bff7a532a2f53 4.3s done
#21 writing layer sha256:72d53e46b6ce55b835eeabf9cf78d75fe14e2e8de62fb4f0a0fd0b8877042a96 0.1s done
#21 writing layer sha256:7d2fb49968b7e3918682def4ca9888d8a91bf1353aa00620858a49055692e5d3
#21 writing layer sha256:7d2fb49968b7e3918682def4ca9888d8a91bf1353aa00620858a49055692e5d3 0.6s done
#21 writing layer sha256:94ad601149b93ad50ddbb3ae725e217ab4cd9161c750e4fb282e1e3aaaf220a3
#21 writing layer sha256:94ad601149b93ad50ddbb3ae725e217ab4cd9161c750e4fb282e1e3aaaf220a3 1.2s done
#21 writing layer sha256:981964e21562b282b098c4422d620ec8b7238acbc4092938c0df5f601de4efce 0.1s done
#21 writing layer sha256:984eeb4c911622a69fd307932ac45e22780ea4ea058aacf9483e9c551a592f21
#21 writing layer sha256:984eeb4c911622a69fd307932ac45e22780ea4ea058aacf9483e9c551a592f21 4.6s done
#21 writing layer sha256:a2e59428a21c354e407f0659988d7224268b0e0ba34c5d14be90954daf8bbb05 0.1s done
#21 writing layer sha256:ba5e607a31cc5ce193c2b8859caeb0a84fa86bd4d18910705c85649604b9119e
#21 writing layer sha256:ba5e607a31cc5ce193c2b8859caeb0a84fa86bd4d18910705c85649604b9119e 0.9s done
#21 writing layer sha256:f29e72ee9556728af816f8cb93ad280bf85dca14e39adc2b24f54cf3b569d10f
#21 writing layer sha256:f29e72ee9556728af816f8cb93ad280bf85dca14e39adc2b24f54cf3b569d10f 1.5s done
#21 preparing build cache for export 25.9s done
#21 DONE 25.9s

### BuildKit logs

```text

```
