### ISSUE TITLE
Caching questions

### ISSUE THREAD

**Issue by gf3** [docker/bake-action#36]
Is it currently possible to use [`actions/cache`](https://github.com/actions/cache) with `docker/bake-action` somehow? I notice there is a `no-cache` option, however it doesn't seem to do much between runs.

Ideally I'd like to take advantage of docker layer caching between runs to speed up our deploys. Thank you!

**Comment by crazy-max** [comment]
Hi @gf3, yes you can use cache the same way as [build-push-action](https://github.com/docker/build-push-action/blob/master/docs/advanced/cache.md) through [`--set` flag](https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md#-override-target-configurations-from-command-line---set) or [`set` input](https://github.com/docker/bake-action#customizing) with this action. Here is a quick example using the registry cache with the bake action:

```yaml
name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v2
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1t
      -
        name: Build and push
        uses: docker/bake-action@v1
        with:
          push: true
          set: |
            *.tags=user/app:latest
            *.cache-from=type=registry,ref=user/app:latest
            *.cache-to=type=inline
```

ref: https://github.com/docker/buildx/blob/master/docs/reference/buildx_bake.md

**Comment by gf3** [comment]
thank you! i'll give this a shot

**Comment by gf3** [comment]
works great! i went with local caching:

```yaml
    - name: Build and push to Amazon ECR
      uses: docker/bake-action@v1.4.2
      env:
        NODE_ENV: production
        REPO: ${{ steps.login-ecr.outputs.registry }}
        TAG: ${{ github.sha }}
      with:
        files: docker-bake.hcl
        push: true
        set: |
          *.cache-from=type=local,src=/tmp/.buildx-cache
          *.cache-to=type=local,mode=max,dest=/tmp/.buildx-cache-new

    # Temp fix
    # https://github.com/docker/build-push-action/issues/252
    # https://github.com/moby/buildkit/issues/1896
    - name: Move cache
      run: |
        rm -rf /tmp/.buildx-cache
        mv /tmp/.buildx-cache-new /tmp/.buildx-cache
```

**Comment by dudicoco** [comment]
@crazy-max thank you for the example.

When using a `docker-compose.yaml` file which builds multiple images, would using a single cache source with `*.cache-from/to` cause any issues?

**Comment by crazy-max** [comment]
@dudicoco Yes cache would be invalidated if Dockerfile/context is different but docker/buildx#721 could solve that in the future. In the meantime you have to add a `docker/bake-action` step for each target and a dedicated cache scope.

**Comment by dudicoco** [comment]
@crazy-max glad to hear you will be implementing my idea in https://github.com/docker/buildx/pull/721 :)

In addition to that, do you think it would be possible to add some kind of variable for the target name, in order to avoid repeating the same code?

For example:
```yaml
x-cache:
  from: type=local,src=/tmp/.buildx-cache,scope=${{ .target }}
x-tags:
-  ${DOCKER_REGISTRY:-default}/${{ .target }}:latest 

services:
  app:
    image: ${DOCKER_REGISTRY:-default}/app
    build:
      context: .
      dockerfile: Dockerfile
```

Where `${{ .target }}` would always resolve to the target name, thus avoiding repetition of the same fields over and over.

**Comment by dudicoco** [comment]
@crazy-max now that https://github.com/docker/buildx/pull/721 is merged, when can we expect a release with this added feature?

Thanks

**Comment by ddelange** [comment]
Note that build-push-action can now also use the Github Actions [`type=gha`](https://github.com/docker/build-push-action/blob/v2.10.0/docs/advanced/cache.md#github-cache) exporter. Testing it with bake-action however did not hit any cached layers when running the same job for the same commit twice.

**Comment by dwalters** [comment]
> Note that build-push-action can now also use the Github Actions [`type=gha`](https://github.com/docker/build-push-action/blob/v2.10.0/docs/advanced/cache.md#github-cache) exporter. Testing it with bake-action however did not hit any cached layers when running the same job for the same commit twice.

I ran into the same behavior - the issue is that the [`special environment variables`](https://github.com/tonistiigi/go-actions-cache/blob/master/api.md) for the github action cache are not exposed by default.  As a workaround, you can add the [crazy-max/ghaction-github-runtime@v1](https://github.com/crazy-max/ghaction-github-runtime) action before running bake-action.

I take it bake-action needs a minor update to support them directly.

A minimal workflow to run bake w/ type=gha caching should be like:

```yaml
name: ci
on:
  push:
    branches: ["master"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v1
      - uses: crazy-max/ghaction-github-runtime@v1
      - uses: docker/bake-action@v1.7.0
        with:
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
          push: ${{ github.event_name != 'pull_request' }}
```

**Comment by dudicoco** [comment]
According to https://github.com/docker/buildx/issues/744 `crazy-max/ghaction-github-runtime` is only required when not using this action.
Sounds like a bug to me that caching doesn't work without it when using this action.

@crazy-max can you please clarify?

**Comment by crazy-max** [comment]
@dudicoco 

> According to [docker/buildx#744](https://github.com/docker/buildx/issues/744) `crazy-max/ghaction-github-runtime` is only required when not using this action.
> Sounds like a bug to me if gha caching doesn't work when using this action.

Indeed, `crazy-max/ghaction-github-runtime` is only required if you don't build through an action because GitHub runtime is not exposed for [`run:` instructions](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsrun) like:

```yaml
name: build

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Expose GitHub Runtime
        uses: crazy-max/ghaction-github-runtime@v1
      -
        name: Build
        run: |
          docker buildx build --cache-from=type=gha --cache-to=type=gha .
```
