### ISSUE TITLE
Error: Blocks are not allowed here

### ISSUE THREAD

**Issue by iwilltry42** [docker/bake-action#61]
#### Steps to reproduce this issue

1. Checkout the `enhancement/gh-action` feature branch or the k3d repository to get the following action part: https://github.com/k3d-io/k3d/blob/enhancement/gh-actions/.github/workflows/release.yaml#L143-L154
2. Push some commit to trigger the workflow (or adjust to `workflow_dispatch`)
3. Wait for it to get to the docker-bake-action step

#### Expected behaviour

The bake action step takes the provided docker-bake.hcl and generated bake JSON files and uses them to build the images.
It works with copied JSON output locally using e.g. `docker buildx bake -f ./docker-bake.hcl -f .local/tests/bake.1.json --print release`

#### Actual behaviour

```bash
Bake definition
  /usr/bin/docker buildx bake --file ./docker-bake.hcl --file /tmp/docker-metadata-action-GGKyIw/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-fZ5d0s/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-toPOSl/docker-metadata-action-bake.json --file /tmp/docker-metadata-action-Cqo0nf/docker-metadata-action-bake.json --metadata-file /tmp/docker-build-push-Rpx0C2/metadata-file binary dind proxy tools --print
  ./docker-bake.hcl:2
  --------------------
     1 |     // filled by GitHub Actions
     2 | >>> target "docker-metadata-k3d" {}
     3 |     target "docker-metadata-k3d-dind" {}
     4 |     target "docker-metadata-k3d-proxy" {}
  --------------------
  error: ./docker-bake.hcl:2,1-7: Unexpected "target" block; Blocks are not allowed here., and 3 other diagnostic(s)
  Error: The process '/usr/bin/docker' failed with exit code 1
```
The same thing happened when I still had the `release` group before the target definitions.

### Configuration

* Repository URL (if public): https://github.com/k3d-io/k3d/blob/enhancement/gh-actions/.github/workflows/release.yaml#L143-L154
* Build URL (if public): https://github.com/k3d-io/k3d/runs/5537963666?check_suite_focus=true

Here's the docker-bake.hcl: https://github.com/k3d-io/k3d/blob/enhancement/gh-actions/docker-bake.hcl

<details>
<summary>Workflow Configuration File</summary>

```yml
name: Test & Release

on: push

env:
  IMAGE_REGISTRY: ghcr.io
  IMAGE_BASE_REPO: k3d-io
  IMAGE_PLATFORMS: linux/amd64,linux/arm64,linux/arm/v7
  GO_VERSION: "1.17.x"
  DOCKER_VERSION: "20.10"
    
jobs:
  test-suite:
    name: Full Test Suite
    runs-on: ubuntu-20.04
    steps:
      #... skipped irrelevant steps ...

  release:
    name: Build & Release
    # Only run on tags
    runs-on: ubuntu-20.04
    steps:
      # Setup
      - uses: actions/checkout@v2
      #... skipped irrelevant steps ...
      # Container Image Setup
      - name: Setup Docker
        uses: docker-practice/actions-setup-docker@master
        with:
          docker_version: "${{ env.DOCKER_VERSION }}"
      - name: Log in to the Container registry
        uses: docker/login-action@v1
        with:
          registry: ${{ env.IMAGE_REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      # Gather Docker Metadata
      - name: Docker Metadata k3d-binary
        id: meta-k3d-binary
        env:
          IMAGE_ID: k3d
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_BASE_REPO }}/${{ env.IMAGE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bake-target: docker-metadata-${{ env.IMAGE_ID }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Docker Metadata k3d-dind
        id: meta-k3d-dind
        env:
          IMAGE_ID: k3d
          IMAGE_SUFFIX: "-dind"
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_BASE_REPO }}/${{ env.IMAGE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bake-target: docker-metadata-${{ env.IMAGE_ID }}${{ env.IMAGE_SUFFIX }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
          flavor: |
            suffix=${{ env.IMAGE_SUFFIX }}
      - name: Docker Metadata k3d-proxy
        id: meta-k3d-proxy
        env:
          IMAGE_ID: k3d-proxy
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_BASE_REPO }}/${{ env.IMAGE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bake-target: docker-metadata-${{ env.IMAGE_ID }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      - name: Docker Metadata k3d-tools
        id: meta-k3d-tools
        env:
          IMAGE_ID: k3d-tools
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.IMAGE_REGISTRY }}/${{ env.IMAGE_BASE_REPO }}/${{ env.IMAGE_ID }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          bake-target: docker-metadata-${{ env.IMAGE_ID }}
          tags: |
            type=semver,pattern={{major}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{version}}
            type=ref,event=branch
            type=ref,event=pr
            type=sha
      # Build and Push container images
      - name: Build Images
        uses: docker/bake-action@v1.7.0
        with:
          files: |
            ./docker-bake.hcl
            ${{ steps.meta-k3d-binary.outputs.bake-file }}
            ${{ steps.meta-k3d-dind.outputs.bake-file }}
            ${{ steps.meta-k3d-proxy.outputs.bake-file }}
            ${{ steps.meta-k3d-tools.outputs.bake-file }}
          targets: binary,dind,proxy,tools
          push: false
      #... skipped irrelevant steps ...
```

</details>

### Logs

[logs_200.zip](https://github.com/docker/bake-action/files/8246386/logs_200.zip)
